version: 2.1

orbs:
    android: circleci/android@2.3.0
    node: circleci/node@5.1.0
    browser-tools: circleci/browser-tools@1.4.3
jobs:
    build:
        docker:
            - image: cimg/android:2023.06
        steps:
            - checkout
            - node/install
            - run:
                name: Run node --version & npm --version
                command: |
                    node --version
                    npm --version
            -   run:
                    name: Install grunt
                    command: |
                        npm install -g grunt-cli
                        grunt --version
            - run:
                  name: Install OpenJDK 8
                  command: |
                      sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
                      sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
                      sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
                      echo 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"' >> $BASH_ENV
                      java -version
                      
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                name: Export Chrome to PATH
                command: |
                    export PATH=/usr/bin/google-chrome-stable:$PATH
                    echo $PATH

            - android/restore-gradle-cache:
                  cache-prefix: v1
            - run:
                  name: Echo Java home
                  command: |
                      echo $JAVA_HOME

            - android/save-gradle-cache:
                  cache-prefix: v1
            - run:
                name: Export Chrome to PATH again
                command: |
                    export PATH=/usr/bin/google-chrome-stable:$PATH
                    echo $PATH
            - run:
                name: check chrome installation and path
                command: |
                    echo $PATH
                    ls /usr/bin/
            - run:
                name: echo PATH then before installing grunt, and after and see then Run App Designer in Browser
                command: |
                    echo $PATH
                    npm install grunt --save-dev
                    echo $PATH
                    grunt
workflows:
    build-workflow:
        jobs:
            - build




